name: CI
on: [push, pull_request]
env:
  BASEDIR: https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/main
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: curl -s -S --retry 3 $BASEDIR/tests/install.sh | bash -
      - run: pip install -r requirements_dev.txt
      - run: curl -s -S --retry 3 $BASEDIR/tests/script.sh | bash -
      - run: pytest /tmp/test_requirements.py
      - name: Install Kingfisher Process
        run: |
          git clone https://github.com/open-contracting/kingfisher-process.git /tmp/kingfisher-process
          pip install -r /tmp/kingfisher-process/requirements.txt
      - name: Setup Kingfisher Process database
        run: |
          python /tmp/kingfisher-process/ocdskingfisher-process-cli upgrade-database
          python /tmp/kingfisher-process/ocdskingfisher-process-cli new-collection 'one' '2000-01-01 00:00:00'
          python /tmp/kingfisher-process/ocdskingfisher-process-cli new-collection 'two' '2000-01-01 00:00:00'
          python /tmp/kingfisher-process/ocdskingfisher-process-cli local-load 1 tests/fixtures release_package
          python /tmp/kingfisher-process/ocdskingfisher-process-cli local-load 2 tests/fixtures release_package
        env:
          KINGFISHER_PROCESS_DB_URI: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
      - run: pytest --cov ocdskingfishersummarize --cov manage
        env:
          KINGFISHER_SUMMARIZE_DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
        if: always()
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
